/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControlDefaultAdminRules } from "./AccessControlDefaultAdminRules";
export type { IAccessControlDefaultAdminRules } from "./IAccessControlDefaultAdminRules";
