/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { SCI } from "./contracts/SCI";
export { SCI__factory } from "./factories/contracts/SCI__factory";
