/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Registry__factory } from "./Registry__factory";
export { RegistryV0__factory } from "./RegistryV0__factory";
